# Generated by Django 5.0.5 on 2025-05-22 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(verbose_name='Zaxira soni')),
                ('location', models.CharField(max_length=100, verbose_name='Joylashuvi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='Mahsulot')),
            ],
        ),
    ]
