# Generated by Django 5.0.5 on 2025-05-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_report_product_description_en_product_description_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='report',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='report',
            name='summary_uz',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title_uz',
        ),
    ]
