# Generated by Django 5.0.5 on 2025-05-19 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim')),
                ('image', models.ImageField(default='profiles/default.png', upload_to='profiles/', verbose_name='Profil rasmi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
    ]
